# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("@rules_cc//cc:defs.bzl", "cc_library")

package(
    default_visibility = ["//visibility:public"],
    features = ["layering_check"],
)

licenses(["notice"])

# Prevent clang from optimizing the insides of internal_strlen etc in
# sanitizer_libc.cpp to call strlen. Such an optimization ends up calling the
# sanitizer interceptor causing a infinite loop.
# This copt is set in CMake but missing here.
SANITIZER_COMMON_COPTS = ["-fno-builtin"]

filegroup(
    name = "fuzzer_hdrs",
    srcs = glob(["include/fuzzer/*"]),
)

filegroup(
    name = "orc_rt_hdrs",
    srcs = glob(["include/orc_rt/*"]),
)

filegroup(
    name = "profile_hdrs",
    srcs = glob(["include/profile/*"]),
)

filegroup(
    name = "sanitizer_hdrs",
    srcs = glob(["include/sanitizer/*"]),
)

filegroup(
    name = "xray_hdrs",
    srcs = glob(["include/xray/*"]),
)

filegroup(
    name = "asan_headers",
    srcs = [
        "lib/asan/asan_activation.h",
        "lib/asan/asan_activation_flags.inc",
        "lib/asan/asan_allocator.h",
        "lib/asan/asan_descriptions.h",
        "lib/asan/asan_errors.h",
        "lib/asan/asan_fake_stack.h",
        "lib/asan/asan_flags.h",
        "lib/asan/asan_flags.inc",
        "lib/asan/asan_init_version.h",
        "lib/asan/asan_interceptors.h",
        "lib/asan/asan_interceptors_memintrinsics.h",
        "lib/asan/asan_interface.inc",
        "lib/asan/asan_interface_internal.h",
        "lib/asan/asan_internal.h",
        "lib/asan/asan_mapping.h",
        "lib/asan/asan_poisoning.h",
        "lib/asan/asan_premap_shadow.h",
        "lib/asan/asan_report.h",
        "lib/asan/asan_scariness_score.h",
        "lib/asan/asan_stack.h",
        "lib/asan/asan_stats.h",
        "lib/asan/asan_suppressions.h",
        "lib/asan/asan_thread.h",
    ],
)

filegroup(
    name = "asan_sources",
    srcs = [
        "lib/asan/asan_activation.cpp",
        "lib/asan/asan_allocator.cpp",
        "lib/asan/asan_debugging.cpp",
        "lib/asan/asan_descriptions.cpp",
        "lib/asan/asan_errors.cpp",
        "lib/asan/asan_fake_stack.cpp",
        "lib/asan/asan_flags.cpp",
        "lib/asan/asan_fuchsia.cpp",
        "lib/asan/asan_globals.cpp",
        "lib/asan/asan_globals_win.cpp",
        "lib/asan/asan_interceptors.cpp",
        "lib/asan/asan_interceptors_memintrinsics.cpp",
        "lib/asan/asan_interceptors_vfork.S",  # Not Win32 and not Apple.
        "lib/asan/asan_linux.cpp",
        "lib/asan/asan_mac.cpp",
        "lib/asan/asan_malloc_linux.cpp",
        "lib/asan/asan_malloc_mac.cpp",
        "lib/asan/asan_malloc_win.cpp",
        "lib/asan/asan_memory_profile.cpp",
        "lib/asan/asan_poisoning.cpp",
        "lib/asan/asan_posix.cpp",
        "lib/asan/asan_premap_shadow.cpp",
        "lib/asan/asan_report.cpp",
        "lib/asan/asan_rtl.cpp",
        "lib/asan/asan_shadow_setup.cpp",
        "lib/asan/asan_stack.cpp",
        "lib/asan/asan_stats.cpp",
        "lib/asan/asan_suppressions.cpp",
        "lib/asan/asan_thread.cpp",
        "lib/asan/asan_win.cpp",
    ],
)

filegroup(
    name = "asan_cxx_sources",
    srcs = [
        "lib/asan/asan_new_delete.cpp",
    ],
)

filegroup(
    name = "asan_static_sources",
    srcs = [
        "lib/asan/asan_rtl_static.cpp",
        "lib/asan/asan_rtl_x86_64.S",  # Not Win32 and not Apple.
    ],
)

filegroup(
    name = "asan_preinit_sources",
    srcs = [
        "lib/asan/asan_preinit.cpp",
    ],
)

cc_library(
    name = "clang_rt.asan",
    srcs = [
        ":asan_preinit_sources",
        ":asan_sources",
        ":interception_sources",
        ":lsan_sources",
        ":sanitizer_common_coverage_sources",
        ":sanitizer_common_libc_sources",
        ":sanitizer_common_sources",
        ":sanitizer_common_symbolizer_sources",
        ":ubsan_sources",
    ],
    hdrs = [
        ":asan_headers",
        ":interception_headers",
        ":lsan_headers",
        ":sanitizer_impl_headers",
        ":ubsan_headers",
    ],
    copts = SANITIZER_COMMON_COPTS,
    includes = ["lib"],
    linkstatic = True,
    visibility = ["//visibility:public"],
)

cc_library(
    name = "clang_rt.asan_cxx",
    srcs = [
        ":asan_cxx_sources",
        ":ubsan_cxx_sources",
    ],
    hdrs = [
        ":asan_headers",
        ":interception_headers",
        ":lsan_headers",
        ":sanitizer_impl_headers",
        ":ubsan_headers",
    ],
    includes = ["lib"],
    linkstatic = True,
    visibility = ["//visibility:public"],
)

cc_library(
    name = "clang_rt.asan_static",
    srcs = [
        ":asan_static_sources",
    ],
    hdrs = [
        ":asan_headers",
        ":sanitizer_impl_headers",
    ],
    includes = ["lib"],
    linkstatic = True,
    visibility = ["//visibility:public"],
)

cc_library(
    name = "clang_rt.asan-preinit",
    srcs = [
        ":asan_preinit_sources",
    ],
    hdrs = [
        ":asan_headers",
        ":sanitizer_impl_headers",
    ],
    includes = ["lib"],
    linkstatic = True,
    visibility = ["//visibility:public"],
)

GENERIC_SOURCES = [
    "lib/builtins/absvdi2.c",
    "lib/builtins/absvsi2.c",
    "lib/builtins/absvti2.c",
    "lib/builtins/adddf3.c",
    "lib/builtins/addsf3.c",
    "lib/builtins/addvdi3.c",
    "lib/builtins/addvsi3.c",
    "lib/builtins/addvti3.c",
    "lib/builtins/apple_versioning.c",
    "lib/builtins/ashldi3.c",
    "lib/builtins/ashlti3.c",
    "lib/builtins/ashrdi3.c",
    "lib/builtins/ashrti3.c",
    "lib/builtins/bswapdi2.c",
    "lib/builtins/bswapsi2.c",
    "lib/builtins/clzdi2.c",
    "lib/builtins/clzsi2.c",
    "lib/builtins/clzti2.c",
    "lib/builtins/cmpdi2.c",
    "lib/builtins/cmpti2.c",
    "lib/builtins/comparedf2.c",
    "lib/builtins/comparesf2.c",
    "lib/builtins/ctzdi2.c",
    "lib/builtins/ctzsi2.c",
    "lib/builtins/ctzti2.c",
    "lib/builtins/divdc3.c",
    "lib/builtins/divdf3.c",
    "lib/builtins/divdi3.c",
    "lib/builtins/divmoddi4.c",
    "lib/builtins/divmodsi4.c",
    "lib/builtins/divmodti4.c",
    "lib/builtins/divsc3.c",
    "lib/builtins/divsf3.c",
    "lib/builtins/divsi3.c",
    "lib/builtins/divti3.c",
    "lib/builtins/extendsfdf2.c",
    "lib/builtins/extendhfsf2.c",
    "lib/builtins/ffsdi2.c",
    "lib/builtins/ffssi2.c",
    "lib/builtins/ffsti2.c",
    "lib/builtins/fixdfdi.c",
    "lib/builtins/fixdfsi.c",
    "lib/builtins/fixdfti.c",
    "lib/builtins/fixsfdi.c",
    "lib/builtins/fixsfsi.c",
    "lib/builtins/fixsfti.c",
    "lib/builtins/fixunsdfdi.c",
    "lib/builtins/fixunsdfsi.c",
    "lib/builtins/fixunsdfti.c",
    "lib/builtins/fixunssfdi.c",
    "lib/builtins/fixunssfsi.c",
    "lib/builtins/fixunssfti.c",
    "lib/builtins/floatdidf.c",
    "lib/builtins/floatdisf.c",
    "lib/builtins/floatsidf.c",
    "lib/builtins/floatsisf.c",
    "lib/builtins/floattidf.c",
    "lib/builtins/floattisf.c",
    "lib/builtins/floatundidf.c",
    "lib/builtins/floatundisf.c",
    "lib/builtins/floatunsidf.c",
    "lib/builtins/floatunsisf.c",
    "lib/builtins/floatuntidf.c",
    "lib/builtins/floatuntisf.c",
    "lib/builtins/fp_mode.c",
    "lib/builtins/int_util.c",
    "lib/builtins/lshrdi3.c",
    "lib/builtins/lshrti3.c",
    "lib/builtins/moddi3.c",
    "lib/builtins/modsi3.c",
    "lib/builtins/modti3.c",
    "lib/builtins/muldc3.c",
    "lib/builtins/muldf3.c",
    "lib/builtins/muldi3.c",
    "lib/builtins/mulodi4.c",
    "lib/builtins/mulosi4.c",
    "lib/builtins/muloti4.c",
    "lib/builtins/mulsc3.c",
    "lib/builtins/mulsf3.c",
    "lib/builtins/multi3.c",
    "lib/builtins/mulvdi3.c",
    "lib/builtins/mulvsi3.c",
    "lib/builtins/mulvti3.c",
    "lib/builtins/negdf2.c",
    "lib/builtins/negdi2.c",
    "lib/builtins/negsf2.c",
    "lib/builtins/negti2.c",
    "lib/builtins/negvdi2.c",
    "lib/builtins/negvsi2.c",
    "lib/builtins/negvti2.c",
    "lib/builtins/os_version_check.c",
    "lib/builtins/paritydi2.c",
    "lib/builtins/paritysi2.c",
    "lib/builtins/parityti2.c",
    "lib/builtins/popcountdi2.c",
    "lib/builtins/popcountsi2.c",
    "lib/builtins/popcountti2.c",
    "lib/builtins/powidf2.c",
    "lib/builtins/powisf2.c",
    "lib/builtins/subdf3.c",
    "lib/builtins/subsf3.c",
    "lib/builtins/subvdi3.c",
    "lib/builtins/subvsi3.c",
    "lib/builtins/subvti3.c",
    "lib/builtins/trampoline_setup.c",
    "lib/builtins/truncdfhf2.c",
    "lib/builtins/truncdfsf2.c",
    "lib/builtins/truncsfhf2.c",
    "lib/builtins/ucmpdi2.c",
    "lib/builtins/ucmpti2.c",
    "lib/builtins/udivdi3.c",
    "lib/builtins/udivmoddi4.c",
    "lib/builtins/udivmodsi4.c",
    "lib/builtins/udivmodti4.c",
    "lib/builtins/udivsi3.c",
    "lib/builtins/udivti3.c",
    "lib/builtins/umoddi3.c",
    "lib/builtins/umodsi3.c",
    "lib/builtins/umodti3.c",

    # Not Fuchsia and not a bare-metal build.
    "lib/builtins/emutls.c",
    "lib/builtins/enable_execute_stack.c",
    "lib/builtins/eprintf.c",

    # Not sure whether we want atomic in this or separately.
    "lib/builtins/atomic.c",

    # Not sure whether this is for libunwind or gcc_s. gotta check.
    "lib/builtins/gcc_personality_v0.c",

    # Not Fuchsia.
    "lib/builtins/clear_cache.c",
]

GENERIC_TF_SOURCES = [
    "lib/builtins/addtf3.c",
    "lib/builtins/comparetf2.c",
    "lib/builtins/divtc3.c",
    "lib/builtins/divtf3.c",
    "lib/builtins/extenddftf2.c",
    "lib/builtins/extendhftf2.c",
    "lib/builtins/extendsftf2.c",
    "lib/builtins/fixtfdi.c",
    "lib/builtins/fixtfsi.c",
    "lib/builtins/fixtfti.c",
    "lib/builtins/fixunstfdi.c",
    "lib/builtins/fixunstfsi.c",
    "lib/builtins/fixunstfti.c",
    "lib/builtins/floatditf.c",
    "lib/builtins/floatsitf.c",
    "lib/builtins/floattitf.c",
    "lib/builtins/floatunditf.c",
    "lib/builtins/floatunsitf.c",
    "lib/builtins/floatuntitf.c",
    "lib/builtins/multc3.c",
    "lib/builtins/multf3.c",
    "lib/builtins/powitf2.c",
    "lib/builtins/subtf3.c",
    "lib/builtins/trunctfdf2.c",
    "lib/builtins/trunctfhf2.c",
    "lib/builtins/trunctfsf2.c",
]

X86_ARCH_SOURCES = [
    "lib/builtins/cpu_model/x86.c",
    "lib/builtins/i386/fp_mode.c",  # Used on 64-bit as well.
]

X86_80_BIT_SOURCES = [
    "lib/builtins/divxc3.c",
    "lib/builtins/extendxftf2.c",
    "lib/builtins/fixxfdi.c",
    "lib/builtins/fixxfti.c",
    "lib/builtins/fixunsxfdi.c",
    "lib/builtins/fixunsxfsi.c",
    "lib/builtins/fixunsxfti.c",
    "lib/builtins/floatdixf.c",
    "lib/builtins/floattixf.c",
    "lib/builtins/floatundixf.c",
    "lib/builtins/floatuntixf.c",
    "lib/builtins/mulxc3.c",
    "lib/builtins/powixf2.c",
    "lib/builtins/trunctfxf2.c",
]

X86_64_SOURCES = GENERIC_SOURCES + GENERIC_TF_SOURCES + X86_ARCH_SOURCES + X86_80_BIT_SOURCES + [
    "lib/builtins/x86_64/floatdidf.c",
    "lib/builtins/x86_64/floatdisf.c",
    "lib/builtins/x86_64/floatundidf.S",
    "lib/builtins/x86_64/floatundisf.S",
    "lib/builtins/x86_64/floatdixf.c",
    "lib/builtins/x86_64/floatundixf.S",
]

BUILTINS_HEADERS = [
    "lib/builtins/assembly.h",
    "lib/builtins/cpu_model/cpu_model.h",
    "lib/builtins/fp_add_impl.inc",
    "lib/builtins/fp_compare_impl.inc",
    "lib/builtins/fp_div_impl.inc",
    "lib/builtins/fp_extend.h",
    "lib/builtins/fp_extend_impl.inc",
    "lib/builtins/fp_fixint_impl.inc",
    "lib/builtins/fp_fixuint_impl.inc",
    "lib/builtins/fp_lib.h",
    "lib/builtins/fp_mode.h",
    "lib/builtins/fp_mul_impl.inc",
    "lib/builtins/fp_trunc.h",
    "lib/builtins/fp_trunc_impl.inc",
    "lib/builtins/int_div_impl.inc",
    "lib/builtins/int_endianness.h",
    "lib/builtins/int_lib.h",
    "lib/builtins/int_math.h",
    "lib/builtins/int_mulo_impl.inc",
    "lib/builtins/int_mulv_impl.inc",
    "lib/builtins/int_to_fp.h",
    "lib/builtins/int_to_fp_impl.inc",
    "lib/builtins/int_types.h",
    "lib/builtins/int_util.h",
]

cc_library(
    name = "builtins",
    srcs = X86_64_SOURCES,
    hdrs = BUILTINS_HEADERS,
    includes = ["lib"],
    linkstatic = True,
    visibility = ["//visibility:public"],
)

cc_library(
    name = "clang_rt.builtins",
    srcs = X86_64_SOURCES,
    hdrs = BUILTINS_HEADERS,
    includes = ["lib"],
    linkstatic = True,
    visibility = ["//visibility:public"],
)

cc_library(
    name = "crtbegin",
    srcs = ["lib/builtins/crtbegin.c"],
    defines = ["EH_USE_FRAME_REGISTRY"],
    linkstatic = True,
    visibility = ["//visibility:public"],
)

cc_library(
    name = "crtend",
    srcs = ["lib/builtins/crtend.c"],
    linkstatic = True,
    visibility = ["//visibility:public"],
)

cc_library(
    name = "crt",
    linkstatic = True,
    visibility = ["//visibility:public"],
    deps = [
        ":crtbegin",
        ":crtend",
    ],
)

cc_library(
    name = "orc_rt_common_headers",
    hdrs = [
        "lib/orc/adt.h",
        "lib/orc/bitmask_enum.h",
        "lib/orc/common.h",
        "lib/orc/compiler.h",
        "lib/orc/debug.h",
        "lib/orc/endianness.h",
        "lib/orc/error.h",
        "lib/orc/executor_address.h",
        "lib/orc/executor_symbol_def.h",
        "lib/orc/interval_map.h",
        "lib/orc/interval_set.h",
        "lib/orc/jit_dispatch.h",
        "lib/orc/record_section_tracker.h",
        "lib/orc/rtti.h",
        "lib/orc/simple_packed_serialization.h",
        "lib/orc/stl_extras.h",
        "lib/orc/string_pool.h",
        "lib/orc/unique_function.h",
        "lib/orc/wrapper_function_utils.h",
    ],
    strip_include_prefix = "lib/orc",
)

cc_library(
    name = "orc_rt",
    srcs = [
        "lib/orc/debug.cpp",
        "lib/orc/dlfcn_wrapper.cpp",
        "lib/orc/log_error_to_stderr.cpp",
        "lib/orc/rtti.cpp",
        "lib/orc/run_program_wrapper.cpp",
    ] + select({
        "@platforms//os:macos": [
            "lib/orc/macho_platform.cpp",
            "lib/orc/macho_platform.h",
            "lib/orc/macho_tlv.arm64.S",
            "lib/orc/macho_tlv.x86-64.S",
        ],
        "@platforms//os:linux": [
            "lib/orc/elfnix_platform.cpp",
            "lib/orc/elfnix_platform.h",
            "lib/orc/elfnix_tls.aarch64.S",
            "lib/orc/elfnix_tls.ppc64.S",
            "lib/orc/elfnix_tls.x86-64.S",
        ],
    }),
    hdrs = glob(["include/orc_rt/*.h"]),
    includes = ["include"],
)

filegroup(
    name = "interception_headers",
    srcs = [
        "lib/interception/interception.h",
        "lib/interception/interception_linux.h",
        "lib/interception/interception_mac.h",
        "lib/interception/interception_win.h",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "interception_sources",
    srcs = [
        "lib/interception/interception_linux.cpp",
        "lib/interception/interception_mac.cpp",
        "lib/interception/interception_type_test.cpp",
        "lib/interception/interception_win.cpp",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "lsan_headers",
    srcs = [
        "lib/lsan/lsan.h",
        "lib/lsan/lsan_allocator.h",
        "lib/lsan/lsan_common.h",
        "lib/lsan/lsan_flags.inc",
        "lib/lsan/lsan_posix.h",  # Missing in CMake.
        "lib/lsan/lsan_thread.h",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "lsan_sources",
    srcs = [
        "lib/lsan/lsan_common.cpp",
        "lib/lsan/lsan_common_fuchsia.cpp",
        "lib/lsan/lsan_common_linux.cpp",
        "lib/lsan/lsan_common_mac.cpp",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "clang_rt.lsan",
    srcs = [
        "lib/lsan/lsan.cpp",
        "lib/lsan/lsan_allocator.cpp",
        "lib/lsan/lsan_fuchsia.cpp",
        "lib/lsan/lsan_interceptors.cpp",
        "lib/lsan/lsan_linux.cpp",
        "lib/lsan/lsan_mac.cpp",
        "lib/lsan/lsan_malloc_mac.cpp",
        "lib/lsan/lsan_posix.cpp",
        "lib/lsan/lsan_preinit.cpp",
        "lib/lsan/lsan_thread.cpp",
        ":interception_sources",
        ":lsan_sources",
        ":sanitizer_common_coverage_sources",
        ":sanitizer_common_libc_sources",
        ":sanitizer_common_sources",
        ":sanitizer_common_symbolizer_sources",
    ],
    hdrs = [
        ":interception_headers",
        ":lsan_headers",
        ":sanitizer_impl_headers",
    ],
    copts = SANITIZER_COMMON_COPTS,
    includes = ["lib"],
    linkstatic = True,
    visibility = ["//visibility:public"],
)

filegroup(
    name = "msan_headers",
    srcs = [
        "lib/msan/msan.h",
        "lib/msan/msan_allocator.h",
        "lib/msan/msan_chained_origin_depot.h",
        "lib/msan/msan_dl.h",
        "lib/msan/msan_flags.h",
        "lib/msan/msan_flags.inc",
        "lib/msan/msan_interface_internal.h",
        "lib/msan/msan_origin.h",
        "lib/msan/msan_poisoning.h",
        "lib/msan/msan_report.h",
        "lib/msan/msan_thread.h",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "clang_rt.msan",
    srcs = [
        "lib/msan/msan.cpp",
        "lib/msan/msan_allocator.cpp",
        "lib/msan/msan_chained_origin_depot.cpp",
        "lib/msan/msan_dl.cpp",
        "lib/msan/msan_interceptors.cpp",
        "lib/msan/msan_linux.cpp",
        "lib/msan/msan_poisoning.cpp",
        "lib/msan/msan_report.cpp",
        "lib/msan/msan_thread.cpp",
        ":interception_sources",
        ":sanitizer_common_coverage_sources",
        ":sanitizer_common_libc_sources",
        ":sanitizer_common_sources",
        ":sanitizer_common_symbolizer_sources",
        ":ubsan_sources",
    ],
    hdrs = [
        ":interception_headers",
        ":msan_headers",
        ":sanitizer_impl_headers",
        ":ubsan_headers",
    ],
    copts = SANITIZER_COMMON_COPTS,
    includes = ["lib"],
    linkstatic = True,
    visibility = ["//visibility:public"],
)

cc_library(
    name = "clang_rt.msan_cxx",
    srcs = [
        "lib/msan/msan_new_delete.cpp",
        ":ubsan_cxx_sources",
    ],
    hdrs = [
        ":interception_headers",
        ":msan_headers",
        ":sanitizer_impl_headers",
        ":ubsan_headers",
    ],
    includes = ["lib"],
    linkstatic = True,
    visibility = ["//visibility:public"],
)

filegroup(
    name = "sanitizer_impl_headers",
    srcs = glob([
        "lib/sanitizer_common/*.h",
        "lib/sanitizer_common/*.inc",
        "lib/sanitizer_common/*.inc.S",
    ]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "sanitizer_common_sources",
    srcs = [
        "lib/sanitizer_common/sanitizer_allocator.cpp",
        "lib/sanitizer_common/sanitizer_common.cpp",
        "lib/sanitizer_common/sanitizer_deadlock_detector1.cpp",
        "lib/sanitizer_common/sanitizer_deadlock_detector2.cpp",
        "lib/sanitizer_common/sanitizer_errno.cpp",
        "lib/sanitizer_common/sanitizer_file.cpp",
        "lib/sanitizer_common/sanitizer_flags.cpp",
        "lib/sanitizer_common/sanitizer_flag_parser.cpp",
        "lib/sanitizer_common/sanitizer_fuchsia.cpp",
        "lib/sanitizer_common/sanitizer_libc.cpp",
        "lib/sanitizer_common/sanitizer_libignore.cpp",
        "lib/sanitizer_common/sanitizer_linux.cpp",
        "lib/sanitizer_common/sanitizer_linux_s390.cpp",
        "lib/sanitizer_common/sanitizer_mac.cpp",
        "lib/sanitizer_common/sanitizer_mutex.cpp",
        "lib/sanitizer_common/sanitizer_netbsd.cpp",
        "lib/sanitizer_common/sanitizer_platform_limits_freebsd.cpp",
        "lib/sanitizer_common/sanitizer_platform_limits_linux.cpp",
        "lib/sanitizer_common/sanitizer_platform_limits_netbsd.cpp",
        "lib/sanitizer_common/sanitizer_platform_limits_posix.cpp",
        "lib/sanitizer_common/sanitizer_platform_limits_solaris.cpp",
        "lib/sanitizer_common/sanitizer_posix.cpp",
        "lib/sanitizer_common/sanitizer_printf.cpp",
        "lib/sanitizer_common/sanitizer_procmaps_common.cpp",
        "lib/sanitizer_common/sanitizer_procmaps_bsd.cpp",
        "lib/sanitizer_common/sanitizer_procmaps_fuchsia.cpp",
        "lib/sanitizer_common/sanitizer_procmaps_linux.cpp",
        "lib/sanitizer_common/sanitizer_procmaps_mac.cpp",
        "lib/sanitizer_common/sanitizer_procmaps_solaris.cpp",
        "lib/sanitizer_common/sanitizer_range.cpp",
        "lib/sanitizer_common/sanitizer_solaris.cpp",
        "lib/sanitizer_common/sanitizer_stoptheworld_fuchsia.cpp",
        "lib/sanitizer_common/sanitizer_stoptheworld_mac.cpp",
        "lib/sanitizer_common/sanitizer_stoptheworld_win.cpp",
        "lib/sanitizer_common/sanitizer_suppressions.cpp",
        "lib/sanitizer_common/sanitizer_tls_get_addr.cpp",
        "lib/sanitizer_common/sanitizer_thread_arg_retval.cpp",
        "lib/sanitizer_common/sanitizer_thread_history.cpp",
        "lib/sanitizer_common/sanitizer_thread_registry.cpp",
        "lib/sanitizer_common/sanitizer_type_traits.cpp",
        "lib/sanitizer_common/sanitizer_win.cpp",
        "lib/sanitizer_common/sanitizer_win_interception.cpp",

        # Always termination.
        "lib/sanitizer_common/sanitizer_termination.cpp",
    ],
)

filegroup(
    name = "sanitizer_common_no_libc_sources",
    srcs = [
        "lib/sanitizer_common/sanitizer_common_nolibc.cpp",
    ],
)

filegroup(
    name = "sanitizer_common_libc_sources",
    srcs = [
        "lib/sanitizer_common/sanitizer_allocator_checks.cpp",
        "lib/sanitizer_common/sanitizer_common_libcdep.cpp",
        "lib/sanitizer_common/sanitizer_dl.cpp",
        "lib/sanitizer_common/sanitizer_linux_libcdep.cpp",
        "lib/sanitizer_common/sanitizer_mac_libcdep.cpp",
        "lib/sanitizer_common/sanitizer_posix_libcdep.cpp",
        "lib/sanitizer_common/sanitizer_stoptheworld_linux_libcdep.cpp",
        "lib/sanitizer_common/sanitizer_stoptheworld_netbsd_libcdep.cpp",
    ],
)

filegroup(
    name = "sanitizer_common_coverage_sources",
    srcs = [
        "lib/sanitizer_common/sancov_flags.cpp",
        "lib/sanitizer_common/sanitizer_coverage_fuchsia.cpp",
        "lib/sanitizer_common/sanitizer_coverage_libcdep_new.cpp",
        "lib/sanitizer_common/sanitizer_coverage_win_sections.cpp",
    ],
)

filegroup(
    name = "sanitizer_common_symbolizer_sources",
    srcs = [
        "lib/sanitizer_common/sanitizer_allocator_report.cpp",
        "lib/sanitizer_common/sanitizer_chained_origin_depot.cpp",
        "lib/sanitizer_common/sanitizer_stack_store.cpp",
        "lib/sanitizer_common/sanitizer_stackdepot.cpp",
        "lib/sanitizer_common/sanitizer_stacktrace.cpp",
        "lib/sanitizer_common/sanitizer_stacktrace_libcdep.cpp",
        "lib/sanitizer_common/sanitizer_stacktrace_printer.cpp",
        "lib/sanitizer_common/sanitizer_stacktrace_sparc.cpp",
        "lib/sanitizer_common/sanitizer_symbolizer.cpp",
        "lib/sanitizer_common/sanitizer_symbolizer_libbacktrace.cpp",
        "lib/sanitizer_common/sanitizer_symbolizer_libcdep.cpp",
        "lib/sanitizer_common/sanitizer_symbolizer_mac.cpp",
        "lib/sanitizer_common/sanitizer_symbolizer_markup.cpp",
        "lib/sanitizer_common/sanitizer_symbolizer_markup_fuchsia.cpp",
        "lib/sanitizer_common/sanitizer_symbolizer_posix_libcdep.cpp",
        "lib/sanitizer_common/sanitizer_symbolizer_report.cpp",
        "lib/sanitizer_common/sanitizer_symbolizer_report_fuchsia.cpp",
        "lib/sanitizer_common/sanitizer_symbolizer_win.cpp",
        "lib/sanitizer_common/sanitizer_unwind_fuchsia.cpp",
        "lib/sanitizer_common/sanitizer_unwind_linux_libcdep.cpp",
        "lib/sanitizer_common/sanitizer_unwind_win.cpp",
    ],
)

filegroup(
    name = "tsan_headers",
    srcs = [
        "lib/tsan/rtl/tsan_adaptive_delay.h",
        "lib/tsan/rtl/tsan_defs.h",
        "lib/tsan/rtl/tsan_dense_alloc.h",
        "lib/tsan/rtl/tsan_fd.h",
        "lib/tsan/rtl/tsan_flags.h",
        "lib/tsan/rtl/tsan_flags.inc",
        "lib/tsan/rtl/tsan_ignoreset.h",
        "lib/tsan/rtl/tsan_ilist.h",
        "lib/tsan/rtl/tsan_interceptors.h",
        "lib/tsan/rtl/tsan_interface.h",
        "lib/tsan/rtl/tsan_interface.inc",
        "lib/tsan/rtl/tsan_interface_ann.h",
        "lib/tsan/rtl/tsan_interface_java.h",
        "lib/tsan/rtl/tsan_mman.h",
        "lib/tsan/rtl/tsan_mutexset.h",
        "lib/tsan/rtl/tsan_platform.h",
        "lib/tsan/rtl/tsan_ppc_regs.h",
        "lib/tsan/rtl/tsan_report.h",
        "lib/tsan/rtl/tsan_rtl.h",
        "lib/tsan/rtl/tsan_shadow.h",
        "lib/tsan/rtl/tsan_stack_trace.h",
        "lib/tsan/rtl/tsan_suppressions.h",
        "lib/tsan/rtl/tsan_symbolize.h",
        "lib/tsan/rtl/tsan_sync.h",
        "lib/tsan/rtl/tsan_trace.h",
        "lib/tsan/rtl/tsan_vector_clock.h",
    ],
)

cc_library(
    name = "clang_rt.tsan",
    srcs = [
        # TSAN_SOURCES.
        "lib/tsan/rtl/tsan_adaptive_delay.cpp",
        "lib/tsan/rtl/tsan_debugging.cpp",
        "lib/tsan/rtl/tsan_external.cpp",
        "lib/tsan/rtl/tsan_fd.cpp",
        "lib/tsan/rtl/tsan_flags.cpp",
        "lib/tsan/rtl/tsan_ignoreset.cpp",
        "lib/tsan/rtl/tsan_interceptors_memintrinsics.cpp",
        "lib/tsan/rtl/tsan_interceptors_posix.cpp",
        "lib/tsan/rtl/tsan_interface.cpp",
        "lib/tsan/rtl/tsan_interface_ann.cpp",
        "lib/tsan/rtl/tsan_interface_atomic.cpp",
        "lib/tsan/rtl/tsan_interface_java.cpp",
        "lib/tsan/rtl/tsan_malloc_mac.cpp",
        "lib/tsan/rtl/tsan_md5.cpp",
        "lib/tsan/rtl/tsan_mman.cpp",
        "lib/tsan/rtl/tsan_mutexset.cpp",
        "lib/tsan/rtl/tsan_report.cpp",
        "lib/tsan/rtl/tsan_rtl.cpp",
        "lib/tsan/rtl/tsan_rtl_access.cpp",
        "lib/tsan/rtl/tsan_rtl_mutex.cpp",
        "lib/tsan/rtl/tsan_rtl_proc.cpp",
        "lib/tsan/rtl/tsan_rtl_report.cpp",
        "lib/tsan/rtl/tsan_rtl_thread.cpp",
        "lib/tsan/rtl/tsan_stack_trace.cpp",
        "lib/tsan/rtl/tsan_suppressions.cpp",
        "lib/tsan/rtl/tsan_symbolize.cpp",
        "lib/tsan/rtl/tsan_sync.cpp",
        "lib/tsan/rtl/tsan_vector_clock.cpp",

        # TSAN_ASM_SOURCES.
        "lib/tsan/rtl/tsan_rtl_amd64.S",

        # TSAN_PREINIT_SOURCES.
        "lib/tsan/rtl/tsan_preinit.cpp",

        # Linux sources.
        "lib/tsan/rtl/tsan_platform_linux.cpp",
        "lib/tsan/rtl/tsan_platform_posix.cpp",
        ":interception_sources",
        ":ubsan_sources",
        ":sanitizer_common_sources",
        ":sanitizer_common_libc_sources",
        ":sanitizer_common_coverage_sources",
        ":sanitizer_common_symbolizer_sources",
    ],
    hdrs = [
        ":interception_headers",
        ":sanitizer_impl_headers",
        ":tsan_headers",
        ":ubsan_headers",
    ],
    copts = SANITIZER_COMMON_COPTS,
    includes = ["lib"],
    linkstatic = True,
    visibility = ["//visibility:public"],
)

cc_library(
    name = "clang_rt.tsan_cxx",
    srcs = [
        "lib/tsan/rtl/tsan_new_delete.cpp",
        ":ubsan_cxx_sources",
    ],
    hdrs = [
        ":interception_headers",
        ":sanitizer_impl_headers",
        ":tsan_headers",
        ":ubsan_headers",
    ],
    includes = ["lib"],
    linkstatic = True,
    visibility = ["//visibility:public"],
)

filegroup(
    name = "ubsan_headers",
    srcs = [
        "lib/ubsan/ubsan_checks.inc",
        "lib/ubsan/ubsan_diag.h",
        "lib/ubsan/ubsan_flags.h",
        "lib/ubsan/ubsan_flags.inc",
        "lib/ubsan/ubsan_handlers.h",
        "lib/ubsan/ubsan_handlers_cxx.h",
        "lib/ubsan/ubsan_init.h",
        "lib/ubsan/ubsan_interface.inc",
        "lib/ubsan/ubsan_monitor.h",
        "lib/ubsan/ubsan_platform.h",
        "lib/ubsan/ubsan_signals_standalone.h",
        "lib/ubsan/ubsan_type_hash.h",
        "lib/ubsan/ubsan_value.h",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "ubsan_sources",
    srcs = [
        "lib/ubsan/ubsan_diag.cpp",
        "lib/ubsan/ubsan_flags.cpp",
        "lib/ubsan/ubsan_handlers.cpp",
        "lib/ubsan/ubsan_init.cpp",
        "lib/ubsan/ubsan_monitor.cpp",
        "lib/ubsan/ubsan_value.cpp",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "ubsan_cxx_sources",
    srcs = [
        "lib/ubsan/ubsan_handlers_cxx.cpp",
        "lib/ubsan/ubsan_type_hash.cpp",
        "lib/ubsan/ubsan_type_hash_itanium.cpp",
        "lib/ubsan/ubsan_type_hash_win.cpp",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "ubsan_standalone_sources",
    srcs = [
        "lib/ubsan/ubsan_diag_standalone.cpp",
        "lib/ubsan/ubsan_init_standalone.cpp",
        "lib/ubsan/ubsan_signals_standalone.cpp",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "clang_rt.ubsan_standalone",
    srcs = [
        "lib/ubsan/ubsan_init_standalone_preinit.cpp",
        ":interception_sources",
        ":sanitizer_common_coverage_sources",
        ":sanitizer_common_libc_sources",
        ":sanitizer_common_sources",
        ":sanitizer_common_symbolizer_sources",
        ":ubsan_standalone_sources",
    ],
    hdrs = [
        ":interception_headers",
        ":sanitizer_impl_headers",
        ":ubsan_headers",
    ],
    copts = SANITIZER_COMMON_COPTS,
    includes = ["lib"],
    linkstatic = True,
    visibility = ["//visibility:public"],
)

cc_library(
    name = "clang_rt.ubsan_standalone_cxx",
    srcs = [
        "lib/ubsan/ubsan_init_standalone_preinit.cpp",
        ":ubsan_cxx_sources",
        ":ubsan_standalone_sources",
    ],
    hdrs = [
        ":interception_headers",
        ":sanitizer_impl_headers",
        ":ubsan_headers",
    ],
    includes = ["lib"],
    linkstatic = True,
    visibility = ["//visibility:public"],
)

filegroup(
    name = "asan_ignorelist",
    srcs = [
        "lib/asan/asan_ignorelist.txt",
    ],
)

filegroup(
    name = "hwasan_ignorelist",
    srcs = [
        "lib/hwasan/hwasan_ignorelist.txt",
    ],
)

filegroup(
    name = "msan_ignorelist",
    srcs = [
        "lib/msan/msan_ignorelist.txt",
    ],
)

filegroup(
    name = "cfi_ignorelist",
    srcs = [
        "lib/cfi/cfi_ignorelist.txt",
    ],
)

filegroup(
    name = "fuzzer_installed_hdrs",
    srcs = glob(["include/fuzzer/*.h"]),
)

filegroup(
    name = "profile_installed_hdrs",
    srcs = glob(["include/profile/*.h"]),
)

filegroup(
    name = "sanitizer_installed_hdrs",
    srcs = glob(["include/sanitizer/*.h"]),
)

BUILTINS_CRTBEGIN_SRCS = ["lib/builtins/crtbegin.c"]

filegroup(
    name = "builtins_crtbegin_src",
    srcs = BUILTINS_CRTBEGIN_SRCS,
)

BUILTINS_CRTEND_SRCS = ["lib/builtins/crtend.c"]

filegroup(
    name = "builtins_crtend_src",
    srcs = BUILTINS_CRTEND_SRCS,
)

BUILTINS_HOSTED_SRCS = [
    "lib/builtins/clear_cache.c",
    "lib/builtins/emutls.c",
    "lib/builtins/enable_execute_stack.c",
    "lib/builtins/eprintf.c",
]

# Source files in the builtins library that build on top of libc and are only
# appropriate in hosted environments.
filegroup(
    name = "builtins_hosted_srcs",
    srcs = BUILTINS_HOSTED_SRCS,
)

BUILTINS_BF16_SRCS_PATTERNS = [
    "lib/builtins/*bf*.c",
]

# Source files for the 16-bit Brain floating-point number builtins.
filegroup(
    name = "builtins_bf16_srcs",
    srcs = glob(BUILTINS_BF16_SRCS_PATTERNS),
)

BUILTINS_X86_FP80_SRCS_PATTERNS = [
    # `xc` marks 80-bit complex number builtins.
    "lib/builtins/*xc*.c",

    # `xf` marks 80-bit floating-point builtins.
    "lib/builtins/*xf*.c",
]

# Source files for the 80-bit floating-point and complex number builtins.
filegroup(
    name = "builtins_x86_fp80_srcs",
    srcs = glob(
        BUILTINS_X86_FP80_SRCS_PATTERNS,
        exclude = BUILTINS_BF16_SRCS_PATTERNS,
    ),
)

BUILTINS_TF_SRCS_PATTERNS = [
    # `tc` marks 128-bit complex number builtins.
    "lib/builtins/*tc*.c",

    # `tf` marks 128-bit floating-point builtins.
    "lib/builtins/*tf*.c",
]

BUILTINS_TF_EXCLUDES = (
    BUILTINS_HOSTED_SRCS +
    BUILTINS_BF16_SRCS_PATTERNS +
    BUILTINS_X86_FP80_SRCS_PATTERNS
)

# Source files for the 128-bit floating-point and complex number builtins.
filegroup(
    name = "builtins_tf_srcs",
    srcs = glob(
        BUILTINS_TF_SRCS_PATTERNS,
        exclude = BUILTINS_TF_EXCLUDES,
    ),
)

BUILTNS_ATOMICS_SRCS = ["lib/builtins/atomic.c"]

filegroup(
    name = "builtins_atomics_srcs",
    srcs = BUILTNS_ATOMICS_SRCS + ["lib/builtins/assembly.h"],
)

BUILTINS_MACOS_ATOMIC_SRCS_PATTERNS = [
    "lib/builtins/atomic_*.c",
]

# Source files for macOS atomic builtins.
filegroup(
    name = "builtins_macos_atomic_srcs",
    srcs = glob(BUILTINS_MACOS_ATOMIC_SRCS_PATTERNS),
)

# Apple-platform specific SME source file.
filegroup(
    name = "builtins_aarch64_apple_sme_srcs",
    srcs = ["lib/builtins/aarch64/arm_apple_sme_abi.s"],
)

# Non-Apple platform SME sources. These sources assume function
# multi-versioning, `-fno-builtin`, `__ARM_UNALIGNED` feature support, and FP
# availability. Other configurations will need to add a new filegroup if
# desired.
filegroup(
    name = "builtins_aarch64_sme_srcs",
    srcs = [
        "lib/builtins/aarch64/sme-abi.S",
        "lib/builtins/aarch64/sme-abi-assert.c",
    ] + glob(["lib/builtins/aarch64/sme-libc-opt-*.S"]),
)

# A list of (pat, size, model) tuples for AArch64's outline atomics.
AARCH64_OUTLINE_ATOMICS = [
    (pat, size, model)
    for pat in [
        "cas",
        "swp",
        "ldadd",
        "ldclr",
        "ldeor",
        "ldset",
    ]
    for size in [
        "1",
        "2",
        "4",
        "8",
        "16",
    ]
    for model in [
        "1",
        "2",
        "3",
        "4",
        "5",
    ]
    if pat == "cas" or size != "16"
]

AARCH64_OUTLINE_ATOMICS_FMT = "lib/builtins/aarch64/outline_atomic_{0}{1}_{2}.S"

# lse.S is compiled multiple times with different macros as the input. Model
# this as a genrule producing individual files with the macros at the start.
[[genrule(
    name = "builtins_aarch64_outline_atomic_" + pat + size + "_" + model,
    srcs = ["lib/builtins/aarch64/lse.S"],
    outs = [AARCH64_OUTLINE_ATOMICS_FMT.format(pat, size, model)],
    cmd = (
        "echo '#define L_" + pat + "' >> $(OUTS) && " +
        "echo '#define SIZE " + size + "' >> $(OUTS) && " +
        "echo '#define MODEL " + model + "' >> $(OUTS) && " +
        "cat $(SRCS) >> $(OUTS)"
    ),
)] for (pat, size, model) in AARCH64_OUTLINE_ATOMICS]

# Source files for the AArch64 architecture-specific builtins.
filegroup(
    name = "builtins_aarch64_srcs",
    srcs = [
        "lib/builtins/cpu_model/aarch64.c",
        "lib/builtins/cpu_model/aarch64.h",
    ] + [
        AARCH64_OUTLINE_ATOMICS_FMT.format(pat, size, model)
        for (pat, size, model) in AARCH64_OUTLINE_ATOMICS
    ] + glob(
        [
            "lib/builtins/cpu_model/AArch64*.inc",
            "lib/builtins/cpu_model/aarch64/**/*.inc",
            "lib/builtins/aarch64/*.S",
            "lib/builtins/aarch64/*.c",
            "lib/builtins/aarch64/*.cpp",
            "lib/builtins/aarch64/*.h",
        ],
        allow_empty = True,
        exclude = [
            # This file isn't intended to directly compile, and instead is used
            # above to generate a collection of outline atomic helpers.
            "lib/builtins/aarch64/lse.S",
            # These files are provided by SME-specific file groups above.
            "lib/builtins/aarch64/*sme*",
        ],
    ),
)

BUILTINS_ARM_VFP_SRCS_PATTERNS = [
    "lib/builtins/arm/*vfp*.S",
    "lib/builtins/arm/*vfp*.c",
    "lib/builtins/arm/*vfp*.cpp",
    "lib/builtins/arm/*vfp*.h",
]

# Source files for the ARM VFP-specific builtins.
filegroup(
    name = "builtins_arm_vfp_srcs",
    srcs = glob(
        BUILTINS_ARM_VFP_SRCS_PATTERNS,
        allow_empty = True,
    ),
)

# Source files for the ARM architecture-specific builtins.
filegroup(
    name = "builtins_arm_srcs",
    srcs = glob(
        [
            "lib/builtins/arm/*.S",
            "lib/builtins/arm/*.c",
            "lib/builtins/arm/*.cpp",
            "lib/builtins/arm/*.h",
        ],
        allow_empty = True,
        exclude = BUILTINS_ARM_VFP_SRCS_PATTERNS,
    ),
)

# Source files for the PPC architecture-specific builtins.
filegroup(
    name = "builtins_ppc_srcs",
    srcs = glob(
        [
            "lib/builtins/ppc/*.S",
            "lib/builtins/ppc/*.c",
            "lib/builtins/ppc/*.cpp",
            "lib/builtins/ppc/*.h",
        ],
        allow_empty = True,
    ),
)

# Source files for the RISC-V architecture-specific builtins.
filegroup(
    name = "builtins_riscv_srcs",
    srcs = glob(
        [
            "lib/builtins/riscv/*.S",
            "lib/builtins/riscv/*.c",
            "lib/builtins/riscv/*.cpp",
        ],
        allow_empty = True,
    ),
)

# Source files for the x86 architecture specific builtins (both 32-bit and
# 64-bit).
filegroup(
    name = "builtins_x86_arch_srcs",
    srcs = [
        "lib/builtins/cpu_model/x86.c",
        "lib/builtins/i386/fp_mode.c",
    ],
)

# Source files for the x86-64 architecture specific builtins.
filegroup(
    name = "builtins_x86_64_srcs",
    srcs = glob(
        [
            "lib/builtins/x86_64/*.S",
            "lib/builtins/x86_64/*.c",
            "lib/builtins/x86_64/*.cpp",
            "lib/builtins/x86_64/*.h",
        ],
        allow_empty = True,
    ),
)

# Source files for the 32-bit-specific x86 architecture specific builtins.
filegroup(
    name = "builtins_i386_srcs",
    srcs = glob(
        [
            "lib/builtins/i386/*.S",
            "lib/builtins/i386/*.c",
            "lib/builtins/i386/*.cpp",
            "lib/builtins/i386/*.h",
        ],
        allow_empty = True,
        exclude = [
            # This file is used for both i386 and x86_64 and so included in the
            # broader x86 sources.
            "lib/builtins/i386/fp_mode.c",
        ],
    ),
)

# Source files for portable components of the compiler builtins library.
filegroup(
    name = "builtins_generic_srcs",
    srcs = ["lib/builtins/cpu_model/cpu_model.h"] + glob(
        [
            "lib/builtins/*.c",
            "lib/builtins/*.cpp",
            "lib/builtins/*.h",
            "lib/builtins/*.inc",
        ],
        allow_empty = True,
        exclude = (
            BUILTINS_CRTBEGIN_SRCS +
            BUILTINS_CRTEND_SRCS +
            BUILTINS_TF_EXCLUDES +
            BUILTINS_TF_SRCS_PATTERNS +
            BUILTNS_ATOMICS_SRCS +
            BUILTINS_MACOS_ATOMIC_SRCS_PATTERNS
        ),
    ),
)
